name = "OpenSourceRoutingMachine"
uuid = "19e5a071-0e58-4e20-9e36-393e8533d14d"
license = "MIT"
authors = ["MOVIRO GmbH <info@moviro.com>"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
FlatBuffers = "53afe959-3a16-52fa-a8da-cf864710bae9"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
OSRM_jll = "a74304e1-5a13-544f-adb7-0572470cee19"
libosrmc_jll = "b012619c-76c7-5216-bb6b-491eaf671aba"

[sources]
libosrmc_jll = {rev = "main", url = "https://github.com/jrklasen/libosrmc_jll.jl"}

[compat]
CEnum = "0.5.0"
FlatBuffers = "0.6.2"
OSRM_jll = "6.0.0"
julia = "1.11"
libosrmc_jll = "6.0.0"
