name = "OpenSourceRoutingMachine"
uuid = "19e5a071-0e58-4e20-9e36-393e8533d14d"
license = "MIT"
authors = ["MOVIRO GmbH <info@moviro.com>"]
version = "0.1.0"

[deps]
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
OSRM_jll = "a74304e1-5a13-544f-adb7-0572470cee19"
libosrmc_jll = "b012619c-76c7-5216-bb6b-491eaf671aba"

[sources]
OSRM_jll = {url = "https://github.com/jrklasen/OSRM_jll.jl"}
libosrmc_jll = {url = "https://github.com/jrklasen/libosrmc_jll.jl"}

[compat]
julia = "1.10"
EnumX = "1.0.5"
OSRM_jll = "6.0.0"
libosrmc_jll = "6.0.0"
