name = "OpenSourceRoutingMachineDocs"
uuid = "5e0b7c26-2a7d-4c77-b1c9-7e9d9a7b27f5"
authors = ["MOVIRO GmbH <info@moviro.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
OpenSourceRoutingMachine = "19e5a071-0e58-4e20-9e36-393e8533d14d"

[compat]
Documenter = "1"
